# LIQUID ABT - Kubernetes Base Deployment Configuration

apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquid-abt-app
  labels:
    app: liquid-abt
    component: app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: liquid-abt
      component: app
  template:
    metadata:
      labels:
        app: liquid-abt
        component: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      serviceAccountName: liquid-abt-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: app
        image: liquid-abt:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: jwt-secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: encryption-key
        - name: KRAKEN_API_KEY
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: kraken-api-key
        - name: KRAKEN_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: kraken-private-key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: stripe-webhook-secret
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: sentry-dsn
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: liquid-abt-secrets
              key: slack-bot-token
        - name: NEXT_PUBLIC_APP_URL
          valueFrom:
            configMapKeyRef:
              name: liquid-abt-config
              key: app-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: liquid-abt-logs-pvc
      - name: uploads
        persistentVolumeClaim:
          claimName: liquid-abt-uploads-pvc
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - liquid-abt
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: liquid-abt-service
  labels:
    app: liquid-abt
    component: app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: liquid-abt
    component: app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: liquid-abt-sa
  labels:
    app: liquid-abt

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: liquid-abt-config
  labels:
    app: liquid-abt
data:
  app-url: "https://app.liquidtreasury.business"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liquid-abt-logs-pvc
  labels:
    app: liquid-abt
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liquid-abt-uploads-pvc
  labels:
    app: liquid-abt
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3